Failure # 1 (occurred at 2021-12-21_10-06-02)
Traceback (most recent call last):
  File "E:\anaconda\envs\logitech\lib\site-packages\ray\tune\trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "E:\anaconda\envs\logitech\lib\site-packages\ray\tune\ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "E:\anaconda\envs\logitech\lib\site-packages\ray\_private\client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "E:\anaconda\envs\logitech\lib\site-packages\ray\worker.py", line 1623, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.

